apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: expensy-backend
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: expensy-backend
  template:
    metadata:
      labels:
        app: expensy-backend
    spec:
      containers:
        - name: backend
          image: juliaroesschen/expensy-backend:latest 
          ports:
            - containerPort: 8706
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PASSWORD
