apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP   # Only accessible within the cluster
  selector:
    app: expensy-backend
  ports:
    - protocol: TCP
      port: 80         # Service port; how other pods will reach your backend
      targetPort: 8706 # Must match the container port in your backend Deployment
