apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer   # This will get an external IP (if your cloud provider supports it)
  selector:
    app: expensy-frontend
  ports:
    - protocol: TCP
      port: 80         # External port exposed to users
      targetPort: 3000 # Must match the container port defined in your frontend Deployment
